// Copyright (c) KAITO authors.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// The list of supported vLLM model architectures is embedded from
// vllm_model_arch_list.txt (one architecture name per line), which is
// generated by:
//
//	make generate-vllm-arch-list
//
// See hack/generate_vllm_arch_list.sh for details.

package models

import (
	_ "embed"
	"strings"

	"k8s.io/apimachinery/pkg/util/sets"
)

//go:embed vllm_model_arch_list.txt
var vllmModelArchListTxt string

var vLLMModelArchSet sets.Set[string]

func init() {
	lines := strings.Split(strings.TrimSpace(vllmModelArchListTxt), "\n")
	vLLMModelArchSet = sets.New[string]()
	for _, line := range lines {
		if arch := strings.TrimSpace(line); arch != "" {
			vLLMModelArchSet.Insert(arch)
		}
	}
}
