apiVersion: kaito.sh/v1beta1
kind: Workspace
metadata:
  name: workspace-phi-2
resource:
  instanceType: "Standard_NC24ads_A100_v4"
  labelSelector:
    matchLabels:
      apps: phi-2
inference:
  preset:
    name: "phi-2"
