apiVersion: kaito.sh/v1alpha1
kind: InferenceSet
metadata:
  name: phi-4-mini
spec:
  replicas: 1
  labelSelector:
    matchLabels:
      apps: phi-4-mini
  template:
    resource:
      instanceType: "Standard_NC24ads_A100_v4"
    inference:
      preset:
        name: phi-4-mini-instruct
