apiVersion: kaito.sh/v1beta1
kind: Workspace
metadata:
  name: workspace-deepseek-r1
resource:
  count: 6
  instanceType: Standard_NC80adis_H100_v5
  labelSelector:
    matchLabels:
      apps: deepseek-r1
inference:
  preset:
    name: "deepseek-r1-0528"
