apiVersion: v1
kind: ConfigMap
metadata:
  name: kaito-base-images
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "utils.toYamlStrMap" .Values.commonLabels | nindent 4 }}
data:
  BaseImages: |
    images:
      - name: base
        tag: 0.5.1
        runtimeVersion:
          vllm: 0.25.1
          transformers: 5.14.1
